//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vextractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class original
    {
        public int id { get; set; }
        public int urlid { get; set; }
        public string url { get; set; }
        public string info { get; set; }
        public string site { get; set; }
        public string doc { get; set; }
        public string mark { get; set; }
    }
}
