//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vextractor
{
    using System;
    using System.Collections.Generic;
    
    public partial class weight_info
    {
        public int id { get; set; }
        public Nullable<int> urlid { get; set; }
        public string site { get; set; }
        public string mark { get; set; }
        public string info { get; set; }
        public string parent { get; set; }
        public string current { get; set; }
        public string child { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> samplenumber { get; set; }
    }
}
